#ifndef PERIPHERALS_H
#define PERIPHERALS_H
#include "inc/stm32f030x6.h"

#include <stdint.h>
#include <stdbool.h>

typedef enum {
	PLL_MULT_X2  = RCC_CFGR_PLLMUL2,
	PLL_MULT_X3  = RCC_CFGR_PLLMUL3,
	PLL_MULT_X4  = RCC_CFGR_PLLMUL4,
	PLL_MULT_X5  = RCC_CFGR_PLLMUL5,
	PLL_MULT_X6  = RCC_CFGR_PLLMUL6,
	PLL_MULT_X7  = RCC_CFGR_PLLMUL7,
	PLL_MULT_X8  = RCC_CFGR_PLLMUL8,
	PLL_MULT_X9  = RCC_CFGR_PLLMUL9,
	PLL_MULT_X10 = RCC_CFGR_PLLMUL10,
	PLL_MULT_X11 = RCC_CFGR_PLLMUL11,
	PLL_MULT_X12 = RCC_CFGR_PLLMUL12,
	PLL_MULT_X13 = RCC_CFGR_PLLMUL13,
	PLL_MULT_X14 = RCC_CFGR_PLLMUL14,
	PLL_MULT_X15 = RCC_CFGR_PLLMUL15,
	PLL_MULT_X16 = RCC_CFGR_PLLMUL16
} PLL_MULT_E;

extern volatile uint32_t systick;

void clock_setup(bool external_clk, bool use_pll, PLL_MULT_E pll_mult);

void delay_ms(uint32_t ms);

#endif //PERIPHERALS_H
